send_command:
  fields:
    id:
      required: true
      selector:
        number:
          min: 0
          max: 999999
          mode: box
    cmd:
      required: true
      selector:
        text:

send_bulk:
  fields:
    commands:
      required: true
      selector:
        object:
      example: >
        [{"id": 4107, "cmd": "1 22.5"}, {"id": 4109, "cmd": "2957"}]
